# Generated by Django 4.2 on 2023-04-05 21:35

import django.core.validators
from django.db import migrations, models
import museum_srv.models.area_samara_models
import museum_srv.models.entry_group_models
import museum_srv.models.idle_models
import museum_srv.models.technologies_models
import museum_srv.models.timeline_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaSamara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='static/area_samara/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), museum_srv.models.area_samara_models.AreaSamara.check_file_existence])),
                ('video_duration', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AreaSamaraAutoPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_play', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AreaSamaraCurrentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EntryGroupVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='static/entry_group/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), museum_srv.models.entry_group_models.EntryGroupVideo.check_file_existence])),
                ('video_duration', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FlowMask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Idle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=50)),
                ('state', models.BooleanField()),
                ('video', models.FileField(upload_to='static/idle/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), museum_srv.models.idle_models.Idle.check_file_existence])),
                ('video_duration', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
                ('backstage_video', models.FileField(upload_to='static/technologies/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), museum_srv.models.technologies_models.Technologies.check_file_existence])),
                ('backstage_video_duration', models.CharField(blank=True, max_length=100)),
                ('moving_video', models.FileField(blank=True, upload_to='static/technologies/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), museum_srv.models.technologies_models.Technologies.check_file_existence])),
                ('moving_video_duration', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TechnologiesCurrentLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TechnologiesCurrentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TechnologiesFourth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('fourth_stage_video', models.FileField(upload_to='static/technologies/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), museum_srv.models.technologies_models.TechnologiesFourth.check_file_existence])),
                ('fourth_stage_video_duration', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('video_1', models.FileField(upload_to='static/timeline/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), museum_srv.models.timeline_models.TimeLine.check_file_existence])),
                ('intro_video_1', models.FileField(upload_to='static/timeline/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), museum_srv.models.timeline_models.TimeLine.check_file_existence])),
                ('video_2', models.FileField(upload_to='static/timeline/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), museum_srv.models.timeline_models.TimeLine.check_file_existence])),
                ('intro_video_2', models.FileField(upload_to='static/timeline/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), museum_srv.models.timeline_models.TimeLine.check_file_existence])),
                ('video_1_duration', models.CharField(blank=True, max_length=100)),
                ('intro_video_1_duration', models.CharField(blank=True, max_length=100)),
                ('video_2_duration', models.CharField(blank=True, max_length=100)),
                ('intro_video_2_duration', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimeLineCurrentYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_year', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VideoStandCurrentEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_employee', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VideoStandEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('fame', 'fame'), ('veterans', 'veterans')], max_length=50)),
                ('fio', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='static/employees/images')),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoStandPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=50)),
            ],
        ),
    ]
