# Generated by Django 4.1.1 on 2022-09-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoStandEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=50)),
                ('fio', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
