# Generated by Django 4.1.1 on 2022-10-22 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areasamara',
            name='video',
            field=models.FileField(upload_to='static/area_samara/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
        migrations.AlterField(
            model_name='entrygroupvideo',
            name='video',
            field=models.FileField(upload_to='static/entry_group/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='backstage_video',
            field=models.FileField(upload_to='static/technologies/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='moving_video',
            field=models.FileField(blank=True, upload_to='static/technologies/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
        migrations.AlterField(
            model_name='technologiesfourth',
            name='fourth_stage_video',
            field=models.FileField(upload_to='static/technologies/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='video_1',
            field=models.FileField(upload_to='static/timeline/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='video_2',
            field=models.FileField(upload_to='static/timeline/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
