# Generated by Django 4.1.1 on 2022-10-28 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0002_alter_areasamara_video_alter_entrygroupvideo_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='intro_video_1',
            field=models.FileField(blank=True, upload_to='static/timeline/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
        migrations.AddField(
            model_name='timeline',
            name='intro_video_1_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='timeline',
            name='intro_video_2',
            field=models.FileField(blank=True, upload_to='static/timeline/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
        migrations.AddField(
            model_name='timeline',
            name='intro_video_2_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
