# Generated by Django 4.1.1 on 2022-09-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0002_videostandemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostandemployee',
            name='photo',
            field=models.FilePathField(default='http://localhost/storage/video_stand/fame_1.jpg'),
            preserve_default=False,
        ),
    ]
