# Generated by Django 4.1.1 on 2022-09-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0003_videostandemployee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostandemployee',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
