# Generated by Django 4.1.1 on 2022-11-05 17:56

import django.core.validators
from django.db import migrations, models
import museum_srv.models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0004_alter_timeline_intro_video_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='intro_video_1',
            field=models.FileField(upload_to='static/timeline/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), museum_srv.models.TimeLine.check_file_existing]),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='intro_video_2',
            field=models.FileField(upload_to='static/timeline/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), museum_srv.models.TimeLine.check_file_existing]),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='video_1',
            field=models.FileField(upload_to='static/timeline/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), museum_srv.models.TimeLine.check_file_existing]),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='video_2',
            field=models.FileField(upload_to='static/timeline/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), museum_srv.models.TimeLine.check_file_existing]),
        ),
    ]
