# Generated by Django 4.1.1 on 2022-09-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0005_alter_videostandemployee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videostandemployee',
            name='group',
            field=models.CharField(choices=[('fame', 'fame'), ('veterans', 'veterans')], max_length=50),
        ),
        migrations.AlterField(
            model_name='videostandemployee',
            name='photo',
            field=models.ImageField(upload_to='static/employees/images'),
        ),
    ]
