# Generated by Django 4.1.1 on 2022-11-05 18:12

import django.core.validators
from django.db import migrations, models
import museum_srv.models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0005_alter_timeline_intro_video_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areasamara',
            name='video',
            field=models.FileField(upload_to='static/area_samara/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), museum_srv.models.AreaSamara.check_file_existence]),
        ),
        migrations.AlterField(
            model_name='entrygroupvideo',
            name='video',
            field=models.FileField(upload_to='static/entry_group/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), museum_srv.models.EntryGroupVideo.check_file_existence]),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='backstage_video',
            field=models.FileField(upload_to='static/technologies/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), museum_srv.models.Technologies.check_file_existence]),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='moving_video',
            field=models.FileField(blank=True, upload_to='static/technologies/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), museum_srv.models.Technologies.check_file_existence]),
        ),
        migrations.AlterField(
            model_name='technologiesfourth',
            name='fourth_stage_video',
            field=models.FileField(upload_to='static/technologies/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), museum_srv.models.TechnologiesFourth.check_file_existence]),
        ),
    ]
