# Generated by Django 4.1.1 on 2023-03-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0006_alter_areasamara_video_alter_entrygroupvideo_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoStandWaitingMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_name_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoStandWaitingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_name_video', models.FileField(upload_to='')),
            ],
        ),
    ]
