# Generated by Django 4.1.1 on 2022-09-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0006_alter_videostandemployee_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=4)),
                ('video_1', models.FileField(upload_to='static/timeline/video')),
                ('video_2', models.FileField(upload_to='static/timeline/video')),
            ],
        ),
    ]
