# Generated by Django 4.1.1 on 2022-09-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0007_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
