# Generated by Django 4.1.1 on 2023-03-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0007_videostandwaitingmode_videostandwaitingvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videostandwaitingmode',
            name='record_name_status',
            field=models.BooleanField(default=False),
        ),
    ]
