# Generated by Django 4.1.1 on 2022-09-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0009_alter_timeline_video_1_alter_timeline_video_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='video_1',
            field=models.FileField(upload_to='static/timeline/video'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='video_2',
            field=models.FileField(upload_to='static/timeline/video'),
        ),
        migrations.AlterField(
            model_name='videostandemployee',
            name='photo',
            field=models.ImageField(upload_to='static/employees/images'),
        ),
    ]
