# Generated by Django 4.1.1 on 2023-03-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0009_alter_videostandwaitingmode_record_name_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videostandwaitingmode',
            name='record_name_status',
        ),
        migrations.AddField(
            model_name='videostandwaitingmode',
            name='record_name_mode',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
