# Generated by Django 4.1.1 on 2022-09-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0010_alter_timeline_video_1_alter_timeline_video_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaSamara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='static/area_samara/video')),
            ],
        ),
    ]
