# Generated by Django 4.1.1 on 2023-03-27 18:48

import django.core.validators
from django.db import migrations, models
import museum_srv.models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0010_remove_videostandwaitingmode_record_name_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=50)),
                ('state', models.BooleanField()),
                ('video', models.FileField(upload_to='static/idle/<django.db.models.fields.CharField>/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), museum_srv.models.Idle.check_file_existence])),
                ('video_duration', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='VideoStandWaitingMode',
        ),
        migrations.DeleteModel(
            name='VideoStandWaitingVideo',
        ),
    ]
