# Generated by Django 4.1.1 on 2022-09-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0011_areasamara'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
                ('backstage_video', models.FileField(upload_to='static/technologies/video')),
            ],
        ),
        migrations.CreateModel(
            name='TechnologiesMoving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moving_video', models.FileField(upload_to='static/technologies/video')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
    ]
