# Generated by Django 4.1.1 on 2023-03-27 20:57

import django.core.validators
from django.db import migrations, models
import museum_srv.models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0011_idle_delete_videostandwaitingmode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idle',
            name='video',
            field=models.FileField(upload_to='static/idle/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), museum_srv.models.Idle.check_file_existence]),
        ),
    ]
