# Generated by Django 4.1.1 on 2022-09-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0012_technologies_technologiesmoving'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowMask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask', models.IntegerField()),
            ],
        ),
    ]
