# Generated by Django 4.1.1 on 2022-09-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0013_flowmask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowmask',
            name='mask',
            field=models.CharField(max_length=9),
        ),
    ]
