# Generated by Django 4.1.1 on 2022-10-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0014_alter_flowmask_mask'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologies',
            name='backstage_video_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
