# Generated by Django 4.1.1 on 2022-10-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0015_technologies_backstage_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='areasamara',
            name='video_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='technologiesmoving',
            name='moving_video_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='timeline',
            name='video_1_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='timeline',
            name='video_2_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
