# Generated by Django 4.1.1 on 2022-10-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0016_areasamara_video_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostandemployee',
            name='current_employee',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
