# Generated by Django 4.1.1 on 2022-10-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0017_videostandemployee_current_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TechnologiesMoving',
            new_name='TechnologiesLabel',
        ),
        migrations.RenameField(
            model_name='technologieslabel',
            old_name='moving_video',
            new_name='label_video',
        ),
        migrations.RenameField(
            model_name='technologieslabel',
            old_name='moving_video_duration',
            new_name='label_video_duration',
        ),
    ]
