# Generated by Django 4.1.1 on 2022-10-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0019_technologiesfourth_delete_technologieslabel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areasamara',
            old_name='pipeline',
            new_name='stage',
        ),
        migrations.AlterField(
            model_name='timeline',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
