# Generated by Django 4.1.1 on 2022-10-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0020_rename_pipeline_areasamara_stage_alter_timeline_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoStandCurrentEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_employee', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='videostandemployee',
            name='current_employee',
        ),
    ]
