# Generated by Django 4.1.1 on 2022-10-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0021_videostandcurrentemployee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLineCurrentYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_year', models.CharField(max_length=10)),
            ],
        ),
    ]
