# Generated by Django 4.1.1 on 2022-10-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0023_areasamaracurrentstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologiesCurrentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
            ],
        ),
    ]
