# Generated by Django 4.1.1 on 2022-10-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0024_technologiescurrentstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologiesCurrentLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
    ]
