# Generated by Django 4.1.1 on 2022-10-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0025_technologiescurrentlabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryGroupVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='static/entry_group/video')),
                ('video_duration', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
