# Generated by Django 4.1.1 on 2022-10-18 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum_srv', '0026_entrygroupvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areasamaracurrentstage',
            old_name='current_stage',
            new_name='stage',
        ),
    ]
